---
title: "Is Phenomenological Control related to Illusion Sensitivity"
# If blank, the running header is the title in upper case.
shorttitle: "Illusion Sensitivity and Phenomenological Control"
# Set names and affiliations.
# It is nice to specify everyone's orcid, if possible.
# There can be only one corresponding author, but declaring one is optional.
author:
  - name: Dominique Makowski
    corresponding: true
    orcid: 0000-0001-5375-9967
    email: D.Makowski@sussex.ac.uk
    url: https://realitybending.github.io/
    # Roles are optional. 
    # Select from the CRediT: Contributor Roles Taxonomy https://credit.niso.org/
    # conceptualization, data curation, formal Analysis, funding acquisition, investigation, 
    # methodology, project administration, resources, software, supervision, validation, 
    # visualization, writing, editing
    roles:
      - Conceptualization
      - Data curation
      - formal Analysis
      - Funding acquisition
      - Investigation
      - Methodology
      - Project administration
      - Resources
      - Software
      - Supervision
      - Validation
      - Visualization
      - Writing – original draft
      - Writing – review & editing
    affiliations:
      - id: id1
        name: "University of Sussex"
        # group: Clinical Psychology Program
        department: School of Psychology
        # address: 1234 Capital St.
        # city: Albany
        # region: NY
        # postal-code: 12084-1234
  - name: Ana Neves
    orcid: 0009-0006-0020-7599
    roles:
      - Project administration
      - Data curation
      - Formal Analysis
      - Investigation
      - Visualization
      - Writing – original draft
      - Writing – review & editing
    affiliations: 
      - ref: id1
  - name: Zoltan Dienes
    orcid: 0000-0001-7454-3161
    roles:
      - Supervision
      - Writing – review & editing
    affiliations: 
      - ref: id1
author-note:
  status-changes: 
    # Example: [Author name] is now at [affiliation].
    affiliation-change: ~
    # Example: [Author name] is deceased.
    deceased: ~
  # Disclosures condensed to one paragraph, but you can start a field with two line breaks to break them up: \n\nNew Paragraph
  disclosures:
    # Example: This study was registered at X (Identifier Y).
    study-registration: ~
    # Acknowledge and cite data/materials to be shared.
    data-sharing: ~
    # Example: This article is based on data published in [Reference].
    # Example: This article is based on the dissertation completed by [citation].  
    related-report: ~
    # Example: [Author name] has been a paid consultant for Corporation X, which funded this study.
    conflict-of-interest: ~
    # Example: This study was supported by Grant [Grant Number] from [Funding Source].
    financial-support: ~
    # Example: The authors are grateful to [Person] for [Reason].
    gratitude: ~
    # Example. Because the authors are equal contributors, order of authorship was determined by a fair coin toss.
    authorship-agreements: ~
abstract: "Blablablabla blablabla todo todo todo."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [keyword1, keyword2, keyword3]
# If true, tables and figures are mingled with the text instead of listed at the end of the document.
floatsintext: true
# Numbered lines (.pdf and .docx only)
numbered-lines: true
# File with references
bibliography: bibliography.bib
# Suppress title page
suppress-title-page: false
# Masks references that appear in the masked-citations list
mask: false
masked-citations:
  - schneider2012cattell
  - schneider2015intelligence
# Language options. See https://quarto.org/docs/authoring/language.html
lang: en
language:
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows:"
  references-meta-analysis:
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    documentmode: man
---

```{r}
#| label: setup
#| include: false
library(conflicted)
library(tidyverse)
library(flextable)
library(ftExtra)
library(officer)
library(knitr)

conflicts_prefer(dplyr::filter, .quiet = TRUE)
conflicts_prefer(flextable::separate_header, .quiet = TRUE)
```

Visual Illusions are an interesting type of stimuli highlighting the ease with which our phenomenological conscious experience can become dissociated from physical reality. Their robust and reliable effect makes them useful stimuli to explore how perception is constructed and shaped, and several theoretical models have been put forth to explain how they work. In particular, illusions have been recently reframed using a predictive coding account of perception [@notredame2014] in which the brain optimally combines, using some flavour of Bayesian inference, perceptual inputs with prior knowledge to make sense of ambiguous environments [@friston2010].

Such computational model(s) propose to conceptualize illusions as stimuli providing weak or conflicting sensory evidence [@sundareswara2008; @gershman2012] that bias perception toward prior knowledge. In other words, the weight of priors, in the form of perceptual knowledge about the world (e.g., internalized rules of perspective) is amplified when the sensory input is confusing. For instance, in the Müller-Lyer illusion, we “compute” the two (actually identical) lines as being of different lengths because the line flanked with converging fins is misinterpreted as being further away [@notredame2014]. In this context, measuring sensitivity to illusion can be operationalized as indexing the parameters of the Bayesian inference process (e.g., prior precision).

These accounts also provide a compelling framework to explain existing findings reporting interindividual variability in the sensitivity to illusions. Indeed, several studies suggest a relationship between psychopathology and lower illusion sensitivity. Schizophrenic patients, for instance, constantly exhibit lower scores on visual illusion tasks [@costa2023]. Proposed explanations, under this framework, emphasise alterations in metacognitive components whereby greater confidence is given to sensory evidence over prior knowledge, which show as reduced susceptibility to the effect of illusions [@notredame2014]. While evidence for lower visual sensitivity is less established in autistic individuals [@gori2016], reduced biases in the effects of illusions have also been attributed to diminished influence of top-down processes such as prior knowledge [@mitchell2010] and greater emphasis on sensory information [@palmer2017]. Evidence beyond psychopathology suggests illusion sensitivity variation in the general population, which could be correlated for instance with personality traits such as higher agreeableness and honest-humility [@makowski2023] and open-mindness and flexibility of cognitive control [@shoshina2014].

However, the exact nature of this interindividual variability and its potential origin remains unclear. The somewhat mixed evidence in the literature regarding its generalizability and strength could be related to the variety of the paradigms used and the type of processes being mobilised [@makowski2023]. Indeed, traditional methods frequently focus on participant’s experience by prompting them to assess the difference between two identical targets, estimate the target’s physical properties, or adjust the targets to match a reference stimulus [@todorovic2020]. Relying on metacognitive judgments about one’s subjective experiences adds an additional layer to the measure that might not be desired when attempting to measure illusion sensibility. Moreover, paradigms often face challenges in diversifying the illusory effects (i.e., using multiple stimuli to experimentally manipulate the strength of the illusion) and the illusion types (i.e., using various illusions, such as Müller-Lyer, Ebbinghaus, Delboeuf which might rely on a different admixture of mechanisms), hindering the potential of obtaining a comprehensive, valid, and reliable measure of illusion sensitivity [@makowski2023].

The “Illusion Game” paradigm [@makowski2023] has been recently developed to measure illusion sensitivity to various illusion types through its behavioural impact (on response time and error rate) in a perceptual decision task (where participants have to respond as fast as possible; e.g., “which of the left or right circles is bigger”). The stimuli for different classical illusions are created using the Pyllusion software [@makowski2021], which allows researchers to modulate the strength of the illusion as a continuous dimension, independently from the difficulty of the perceptual task. This paradigm, inspired by psychophysics, lends itself to the computational modelling of illusion sensitivity through its interference effect, hopefully bypassing some of the metacognitive processes at stake in other paradigms.

Interestingly, the fact that inter-individual variability in illusion sensitivity seems to persist in this task suggests that it is not solely explained by metacognitive abilities difference, and gives rise to the following question: is the variability in illusion sensitivity related to low-level perceptual processes (e.g., baseline precision of perceptual priors), or rather to the ability to actively control and “resist” the illusion in a top-town fashion in order to achieve the task at hand (higher-level modulation of the perceptual inference parameters). If the latter is true, then illusion sensitivity measured in contexts with strong task-demand characteristics, e.g., in paradigms where participants’ performance is explicitly or implicitly assessed (i.e., where there is an incentive to downplay the illusion effect) might correlate with one’s ability to alter one’s subjective experience following suggestions - a mechanism referred to as “phenomenological control”.

The idea that we are endowed with the potential to unconsciously alter our subjective experience and distort reality - even momentarily - to meet the goals at hand is not novel. While this phenomenon has been historically often studied under the label of "hypnotisability" - the tendency to alter our conscious experience to match external demands [@lush2021], the term "phenomenological control" (PC) has been recently introduced to disconnect this concept from the potentially negative associations with hypnosis and the misconception that a hypnotic context is necessary for responding to imaginative suggestions [@dienes2022].

To encourage the empirical exploration of our ability and tendency to alter our phenomenological experience and further accelerate investigations away from the hypnotic context, @lush2021 adapted the Sussex-Waterloo Scale of Hypnotisability [SWASH**,** @lush2018] by removing all its references to hypnosis, to measure trait phenomenological control. This newly developed phenomenological control scale (PCS) consists of 10 imaginative suggestions followed by subjective ratings for each suggestion on a 6-point Likert scale and has been demonstrated to be compatible with online experiments [@lush2022].

Interestingly, @lush2022 did test for a relationship between PC and illusion sensitivity using the Müller-Lyer illusion (in which the arrangement of the arrowheads flanking two lines makes them appear as having different lengths), and reported evidence in favour of an absence of correlation between the two measures. This finding was interpreted as indicative of the cognitive impenetrability of illusions, implying that the effect is driven by low-level processes and therefore not influenced by top-down mechanisms such as PC. The goal of this study is thus to replicate the results from @lush2022 pointing to an absence of a relationship between phenomenological control and illusion sensitivity, by generalising them to a different illusion task that would encompass other illusion types.

# **Methods**

## **Participants**

We aim to recruit around 500 [in line with the sample sizes used in @lush2021; @lush2022] adult English native speakers with a desktop device using Prolific (www.prolific.co). Participants will be first presented with an explanatory statement and the consent form, and can proceed by pressing a button to confirm they have read and understood the information. This study will be approved by the ethics board of the School of Psychology of the University of Sussex (XX/XXXX).

## **Procedure**

The experiment’s setup follows the born-open principle [@deleeuw2023]. The online experiment, implemented entirely using JsPsych [@de2015jspsych], has its code stored on GitHub and will leverage the power of the platform to host the experiment for free. Participants’ raw data files are then automatically stored on a European server on OSF; and the deanonymized and ready-to-use data (downloaded from OSF and formatted using a reproducible script) will be made available in the same GitHub repository, alongside the scripts used for the analysis.

Participants will be presented with a consent form followed by demographic questions (gender, education level, age, and ethnicity). Participants will then be administered the PCS and the Illusion Game task (IG) in a counterbalanced order.

**Phenomenological Control Scale (PCS)**. Participants will be asked to put on their headphones and await further auditory instructions. The PCS procedure starts with a recorded introduction explaining that a series of tests will be applied to evaluate how experiences can be created through imagination. This will be followed by 10 suggestions in a fixed order [see @lush2021], such as “now extend your arms ahead of you, with palms facing each other, hands about a foot apart” and “as you sit comfortably in your chair with your eyes closed, a picture of two balls will be displayed on the computer screen”. Once the 10 suggestions are completed, participants will be asked to rate their subjective experiences and response to each suggestion on a 6-points Likert scale. Phenomenological control will be indexed by averaging the scores from the 10 scales.

**Illusion Game**. The task is an adaptation of the one used in @makowski2023 to make it shorter and more reliable, in which participants must make perceptual judgments (e.g., "which red line is the longer") as quickly and accurately as possible. It includes 3 illusion types, namely Ebbinghaus, Müller-Lyer, and Vertical-Horizontal. The procedure encompasses 2 sets of 80 trials for each illusion type. Each set will include, in a random order, the 3 blocks of illusion types, in which trials are separated by a fixation cross, temporally (uniformly sampled duration of 500 - 1000s) and spatially jittered (around the centre of the screen in a radius of a 1 cm) to attenuate its potential usefulness as a reference point. After each illusion type block, a score is presented (computed as a scaled Inverse Efficiency Score) as a gamification mechanism to increase motivation to perform to the best of one’s abilities.

For each illusion type, two continuous dimensions are orthogonally manipulated [see @makowski2021 for details on the rationale and execution], namely task difficulty and illusion strength, so that each trial corresponds to a unique combination. Task difficulty corresponds to the difficulty of the perceptual decision (e.g., if the task is to select the longest red line, task difficulty corresponds to how the lines are objectively different). Illusion strength corresponds to the degree to which the illusion elements (e.g., the black arrow lines in Müller-Lyer) are interfering with the aforementioned task. Note that the illusion effect can be “incongruent” (biasing perception in the direction of the incorrect response) or “congruent” (facilitating, i.e., biasing perception in the direction of the correct response). Participants respond with a key arrow (left vs. right; or up vs. down), and their reaction time (RT) and accuracy are recorded.

Visual illusion sensitivity will be measured as the average error rate in the incongruent condition, separately for the 3 illusion types. Although the error rate is arguably a crude score, which does not take into account the effect of varying illusion strength, the interaction with task difficulty and the possible adjustments in response strategy (speed-accuracy tradeoff), it is also the most simple and easy to reproduce, hence its usage as our primary outcome for the current preregistration.

The two sets of 3 illusion blocks will be separated by 2 short questionnaires acting as a break, namely the IPIP-6 [@sibley2011mini], measuring 6 personality traits with 24 analogue scales items, and the PID-5 [@krueger2011], measuring 5 maladaptive personality traits with 25 Likert scales items.

## **Data Analysis**

The PCS will contain several manipulation check indices to identify problematic participants. Participants should not answer "no balls were presented" when queried about the colour they observed on the screen following the negative visual hallucination suggestion, and should execute at least 5 space presses upon instructions to do so.

Illusion Game outliers will be flagged based on their RT distributions, following the same procedure as in [@makowski2023]. If the RT is collapsed to the left (i.e., has \> ⅓ of ultra-fast responses - typically \< 200 ms) in the first block, the entire participant will be discarded (suggesting that they did not properly do the text), but if only the second block is bad, then only the second block will be discarded (as the illusion sensitivity can still be estimated, albeit with less precision). In addition, the removal of individual trials will also be performed [RT \< 200 ms or \> 3 SD; following @thériault2024].

After removing problematic participants and trials, the outcome measures (PC and VI sensitivity scores) will be computed and the Bayesian correlation (with medium prior on the coefficient, i.e., r-scale parameter set to 1/3) will be computed [using the BayesFactor package; @BayesFactor]**.** Following @lush2022, we expect to collect evidence against (BF10 \<= 1/3) a relationship between PCS and VI sensitivity. Data analysis will be carried out using R, using tidyverse [@tidyverse] and easystats [@easystats; @parameters; @correlation; @bayestestR; @datawizard]. The analysis script and additional information are available at https://github.com/RealityBending/IllusionGamePhenomenologicalControl.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::
